### ISSUE TITLE
R Data Access

### ISSUE THREAD

**Issue by jevanilla** [oceanhackweek/ohw-tutorials#77] opened 2022-08-09 18:31 UTC
- [ ] https://github.com/oceanhackweek/ohw-tutorials/tree/OHW22/01-Tue

**Comment by ocefpaf** [comment] 2022-08-09 18:42
Duplicate of #74. I'd rather if we don't multiply the issues if we can. Do you mind closing this one?

**Comment by jevanilla** [comment] 2022-08-09 19:57
We will also be playing this video in the tutorial:
https://www.youtube.com/watch?v=2ZWFYWMwq1c

**Comment by leewujung** [comment] 2022-08-10 13:48
@jevanilla: Could you please close issue and repost the link you have above to under #74. This one is a duplicate to that and duplicates make repos harder to manager. Thanks!

**Comment by jevanilla** [comment] 2022-08-10 13:54
We will also be playing this video in the tutorial:
https://www.youtube.com/watch?v=2ZWFYWMwq1c

**Comment by jevanilla** [comment] 2022-08-10 13:54
@leewujung

**Comment by ocefpaf** [comment] 2022-08-10 15:59
@jevanilla it seems you are confused. This issue, 77, is newer and duplicate of 74. Let's keep the discussion there. Also, the you need to post the link on 74, not here. You already did that in https://github.com/oceanhackweek/ohw-tutorials/issues/77#issuecomment-1209814341 BTW!

Closing this to avoid more confusion. We have many issues opened and we need to keep the issue tracker tidy as the tutorials are being sent.

**Closed by ocefpaf** 2022-08-10 15:59 UTC
Labels: Notebook/Presentation

**Comment by jevanilla** [comment] 2022-08-16 14:17
> @jevanilla it seems you are confused. This issue, 77, is newer and duplicate of 74. Let's keep the discussion there. Also, the you need to post the link on 74, not here. You already did that in [#77 (comment)](https://github.com/oceanhackweek/ohw-tutorials/issues/77#issuecomment-1209814341) BTW!
> 
> Closing this to avoid more confusion. We have many issues opened and we need to keep the issue tracker tidy as the tutorials are being sent.

@ocefpaf @leewujung Following Filipe's desire to keep the issuer tracker tidy, I think we should close issues that have already been completed https://github.com/oceanhackweek/ohw-tutorials/issues/74 & https://github.com/oceanhackweek/ohw-tutorials/issues/79
